# Generated by Django 2.1.2 on 2018-11-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='BOD',
        ),
    ]
