# Generated by Django 2.1.2 on 2018-11-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patients_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='gender',
        ),
    ]
