# Generated by Django 2.1.2 on 2018-11-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181125_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
