# Generated by Django 2.1.2 on 2018-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_patients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='media/', verbose_name='Photo'),
        ),
    ]
