# Generated by Django 2.1.2 on 2018-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181125_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='dob',
            field=models.DateField(default='1999-11-11'),
        ),
    ]
