# Generated by Django 2.0.9 on 2018-11-26 02:31

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_patients_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
    ]
