# Generated by Django 2.0.9 on 2018-11-26 16:30

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20181126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patients',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='disease_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patients',
            name='docor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='medicine_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
