# Generated by Django 2.0.9 on 2018-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181126_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Photo'),
        ),
    ]
