# Generated by Django 2.0.9 on 2018-11-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20181126_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='lon',
        ),
    ]
