# Generated by Django 2.0.9 on 2018-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20181126_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(default='2018-11-11'),
        ),
    ]
